/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-12-09 16:06:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class beeHelloArticle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/FinalProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ViewPage/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1639051896379L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

   request.setCharacterEncoding("UTF-8");
   String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>beeHelloArticle.jsp</title>\r\n");
      out.write("\r\n");
      out.write("<!-- 모달을 위한 링크 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("   rel=\"stylesheet\"\r\n");
      out.write("   integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\r\n");
      out.write("   crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/*reset*/\r\n");
      out.write("* {margin: 0;padding: 0;}\r\n");
      out.write("body {margin: 0;}\r\n");
      out.write("h1, h2, h3, h4, h5, h6, p, ul, ol, li, dl, dt, dd {margin: 0; padding: 0;}\r\n");
      out.write("h1, h2, h3, h4, h5, h6 {font-weight: 700; }\r\n");
      out.write("a {color: inherit; text-decoration: inherit;}\r\n");
      out.write("img {vertical-align: middle;}\r\n");
      out.write("a img {border: none;}\r\n");
      out.write("li {list-style: none;}\r\n");
      out.write("address, em, i, ul {font-style: normal;}\r\n");
      out.write("\r\n");
      out.write("/*layout*/\r\n");
      out.write(".mo {display: none;}\r\n");
      out.write(".en {font-family: 'Exo 2', sans-serif;}\r\n");
      out.write("body {font-family: 'Noto Sans KR', sans-serif; font-size: 14px;}\r\n");
      out.write(".wrap {margin: 0 auto; }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 아티클 CSS */\r\n");
      out.write("#bbs \r\n");
      out.write("{\r\n");
      out.write("\twidth:600px;\r\n");
      out.write("\tmargin:30px auto;\r\n");
      out.write("\ttext-align:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bbs_title \r\n");
      out.write("{\r\n");
      out.write("\twidth:574px;\r\n");
      out.write("\t/* padding-left:20px; */\r\n");
      out.write("\theight:40px;\r\n");
      out.write("\t/* border:3px solid #D6D4A6; */\r\n");
      out.write("\ttext-align:left;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tline-height:40px;\r\n");
      out.write("\tfont-size:15pt;\r\n");
      out.write("\tmargin-bottom:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bbsArticle \r\n");
      out.write("{\r\n");
      out.write("\twidth:600px;\r\n");
      out.write("\toverflow: visible;\r\n");
      out.write("\tborder-top:3px solid #E6D4A6;\r\n");
      out.write("\tborder-bottom:3px solid #E6D4A6;\r\n");
      out.write("\ttext-align:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bbsArticle_header \r\n");
      out.write("{\r\n");
      out.write("\theight:35px;\r\n");
      out.write("\tline-height:35px;\r\n");
      out.write("\tborder-bottom:2px solid #DBDBDB;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("#bbsArticle dl\r\n");
      out.write("{\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("}\r\n");
      out.write("#bbsArticle dt \r\n");
      out.write("{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\theight:35px;\r\n");
      out.write("\twidth:60px;\r\n");
      out.write("\tline-height:35px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tbackground-color:#EEEEEE;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bbsArticle dd \r\n");
      out.write("{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\theight:35px;\r\n");
      out.write("\twidth:150px;\r\n");
      out.write("\tline-height:35px;\r\n");
      out.write("\ttext-align:left;\r\n");
      out.write("\tpadding-left:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bbsArticle_bottomLine \r\n");
      out.write("{\r\n");
      out.write("\theight:35px;\r\n");
      out.write("\tline-height:35px;\r\n");
      out.write("\tborder-bottom:1px solid #DBDBDB;\r\n");
      out.write("\tclear:both;\r\n");
      out.write("\ttext-align:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bbsArticle_noLine \r\n");
      out.write("{\r\n");
      out.write("\theight:35px;\r\n");
      out.write("\tline-height:35px;\r\n");
      out.write("\tclear:both;\r\n");
      out.write("\ttext-align:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bbsArticle_content \r\n");
      out.write("{\r\n");
      out.write("    overflow: visible;\r\n");
      out.write("    border-bottom:1px solid #DBDBDB;\r\n");
      out.write("    text-align:left;\r\n");
      out.write("    min-height:250px;\r\n");
      out.write("    padding: 20px 60px 20px 60px;\r\n");
      out.write("    word-break:break-all;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bbsArticle_footer \r\n");
      out.write("{\r\n");
      out.write("\tclear:both;\r\n");
      out.write("\theight:32px;\r\n");
      out.write("\tline-height:32px;\r\n");
      out.write("\tmargin-bottom:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bbsArticle_footer #leftFooter\r\n");
      out.write("{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\twidth:300px;\r\n");
      out.write("\ttext-align:left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bbsArticle_footer #rightFooter\r\n");
      out.write("{\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("\twidth:300px;\r\n");
      out.write("\ttext-align:right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btnimg\r\n");
      out.write("{\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 모달 css */\r\n");
      out.write("@import\r\n");
      out.write("   url('https://fonts.googleapis.com/css?family=Exo+2|Noto+Sans+KR&display=swap')\r\n");
      out.write("   ;\r\n");
      out.write("\r\n");
      out.write(".row p {\r\n");
      out.write("   font-size: 10px;\r\n");
      out.write("   margin-left: 3vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row {\r\n");
      out.write("   margin-left: 10%;\r\n");
      out.write("   margin-top: 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-footer {\r\n");
      out.write("   display: flex;\r\n");
      out.write("   flex-wrap: wrap;\r\n");
      out.write("   flex-shrink: 0;\r\n");
      out.write("   align-items: center;\r\n");
      out.write("   justify-content: center;\r\n");
      out.write("   padding: .75rem;\r\n");
      out.write("   border-top: 0px solid #dee2e6;\r\n");
      out.write("   border-bottom-right-radius: calc(.3rem - 1px);\r\n");
      out.write("   border-bottom-left-radius: calc(.3rem - 1px);\r\n");
      out.write("   padding: .75rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-secondary {\r\n");
      out.write("   color: #fff;\r\n");
      out.write("   background-color: #6c757d;\r\n");
      out.write("   border-color: #6c757d;\r\n");
      out.write("   margin-right: 7vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!--  \r\n");
      out.write("\tbeeHelloArticle.jsp\r\n");
      out.write("\t- 동아리 내 게시판 > 가입인사 글 클릭 시 아티클\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<div id=\"bbs\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"bbs_title\">\r\n");
      out.write("\t\t가입인사\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"bbsArticle_bottomLine\">\r\n");
      out.write("\t\t목록\r\n");
      out.write("\t\t이전글\r\n");
      out.write("\t\t다음글\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 동아리원일 때 아닐때 나눠서 버튼 작동하게 해야함!! -->\r\n");
      out.write("\t<!-- modal button -->\r\n");
      out.write("\t<div class=\"btnimg\">\r\n");
      out.write("\t      <a href=\"#\" id=\"modal1\" class=\"btn btn-success btn-sm\"\r\n");
      out.write("\t         data-bs-toggle=\"modal\" data-bs-target=\"#employee_details1\">수정하기</a>\r\n");
      out.write("\t   \r\n");
      out.write("\t      <a href=\"#\" id=\"modal1\" class=\"btn btn-success btn-sm\"\r\n");
      out.write("\t         data-bs-toggle=\"modal\" data-bs-target=\"#employee_details1\">삭제하기</a>\r\n");
      out.write("\t\t<img src=\"\" alt=\"신고이미지\"  />\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("   <!-- Modal -->\r\n");
      out.write("   <!-- 권한 창 -->\r\n");
      out.write("   <div class=\"modal fade\" id=\"employee_details1\" tabindex=\"-1\"\r\n");
      out.write("      aria-labelledby=\"employee_details1\" aria-hidden=\"true\">\r\n");
      out.write("      <div class=\"modal-dialog\">\r\n");
      out.write("         <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("               <h5 class=\"modal-title\" id=\"exampleModalLabel\">권한이 없습니다.</h5>\r\n");
      out.write("               <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("                  aria-label=\"닫기\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div><!-- close Modal  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form>\r\n");
      out.write("\t\t<div id=\"bbsArticle\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"bbsArticle_header\">\r\n");
      out.write("\t\t\t\t게시물의 제목입니다.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"bbsArticle_bottomLine\">\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<dt>작성자</dt>\r\n");
      out.write("\t\t\t\t\t<dd>비클러</dd>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<dt>등록일</dt>\r\n");
      out.write("\t\t\t\t\t<dd>2021-12-05</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"bbsArticle_bottomLine\">\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<dt>댓글수</dt>\r\n");
      out.write("\t\t\t\t\t<dd>51</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t<dt>조회수</dt>\r\n");
      out.write("\t\t\t\t\t<dd>251</dd>\r\n");
      out.write("\t\t\t\t</dl>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"bbsArticle_content\">\r\n");
      out.write("\t\t\t\t<table style=\"width: 600\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"padding: 10px 40px 10px 10px; vertical-align: top; height: 150\">\r\n");
      out.write("\t\t\t\t\t\t\t어쩌구 저쩌구 이러쿵 저러쿵 내용입니다.<br>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div><!-- close #bbsArticle -->\r\n");
      out.write("\t</form><!-- close form -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("</div><!-- close #bbs -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 모달창 스크립트 -->\r\n");
      out.write("\t<script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js\"\r\n");
      out.write("      integrity=\"sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js\"\r\n");
      out.write("      integrity=\"sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
      out.write("   <script>\r\n");
      out.write("      $(document).ready(function()\r\n");
      out.write("      {\r\n");
      out.write("\r\n");
      out.write("         $('#employee_details2').on('beforeShow', function()\r\n");
      out.write("         {\r\n");
      out.write("            console.log('Submodal beforeShow event');\r\n");
      out.write("         }).on('show', function()\r\n");
      out.write("         {\r\n");
      out.write("            console.log('Submodal show event');\r\n");
      out.write("         }).on('beforeHide', function()\r\n");
      out.write("         {\r\n");
      out.write("            console.log('Submodal beforeHide event');\r\n");
      out.write("         }).on('hide', function()\r\n");
      out.write("         {\r\n");
      out.write("            console.log('Submodal hide event');\r\n");
      out.write("         });\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /beeHelloArticle.jsp(286,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("comment.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }
}
