/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-12-08 08:50:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>footer.jsp</title>\r\n");
      out.write("<!-- <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write(" -->\r\n");
      out.write(" <script src=\"https://kit.fontawesome.com/dab690a483.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("/*reset*/\r\n");
      out.write("* {margin: 0;padding: 0;}\r\n");
      out.write("body {margin: 0;}\r\n");
      out.write("h1, h2, h3, h4, h5, h6, p, ul, ol, li, dl, dt, dd {margin: 0; padding: 0;}\r\n");
      out.write("h1, h2, h3, h4, h5, h6 {font-weight: 700; }\r\n");
      out.write("a {color: inherit; text-decoration: inherit;}\r\n");
      out.write("img {vertical-align: middle;}\r\n");
      out.write("a img {border: none;}\r\n");
      out.write("li {list-style: none;}\r\n");
      out.write("address, em, i, ul {font-style: normal;}\r\n");
      out.write("\r\n");
      out.write("/*layout*/\r\n");
      out.write(".mo {display: none;}\r\n");
      out.write(".en {font-family: 'Exo 2', sans-serif;}\r\n");
      out.write("body {font-family: 'Noto Sans KR', sans-serif; font-size: 14px;}\r\n");
      out.write(".wrap {margin: 0 auto; }\r\n");
      out.write("\r\n");
      out.write("*\r\n");
      out.write("{\r\n");
      out.write("   margin: 0;\r\n");
      out.write("   padding: 0;\r\n");
      out.write("   font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer\r\n");
      out.write("{\r\n");
      out.write("    max-height: 30vh;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 300px;\r\n");
      out.write("    bottom: 0px;\r\n");
      out.write("    \r\n");
      out.write("   /*\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   bottom: 0px;\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   height: 300px;\r\n");
      out.write("   display: flex;\r\n");
      out.write("   justify-content: center;\r\n");
      out.write("   */\r\n");
      out.write("   background-color: #FFD34E;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container\r\n");
      out.write("{\r\n");
      out.write("  max-width: 1170px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding-top: 50px;\r\n");
      out.write("  padding-bottom: 0;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  /* min-height: 100%; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-menu\r\n");
      out.write("{\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  height: 180px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".first-box\r\n");
      out.write("{\r\n");
      out.write("  width: 60%;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".second-box\r\n");
      out.write("{\r\n");
      out.write("  width: 40%;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: flex-end;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".column {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("  padding: 0 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sub-title {\r\n");
      out.write("  color: white;\r\n");
      out.write("  font-weight: 900;\r\n");
      out.write("  margin: 20px 0px;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-menu-item\r\n");
      out.write("{\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("  padding-bottom: 15px;\r\n");
      out.write("  padding-top: 3px;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-menu-item:hover\r\n");
      out.write("{\r\n");
      out.write("   color: #105B63;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon-box {\r\n");
      out.write("  width: 54px;\r\n");
      out.write("  height: 54px;\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  margin-right: 15px;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon {\r\n");
      out.write("  font-size: 24px;\r\n");
      out.write("}\r\n");
      out.write(".icon:hover {\r\n");
      out.write("  color: #105B63;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".first-line\r\n");
      out.write("{\r\n");
      out.write("  color: #919496;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: flex-end;\r\n");
      out.write("  font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("          <div class=\"footer-menu\">\r\n");
      out.write("              <div class=\"first-box\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                      <img src=\"./image/logo.png\" width=132>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- <div class=\"column col-3 col-6-medium col-12-small\"> -->\r\n");
      out.write("                  <div class=\"column\">\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"sub-title\">B:CLE</div>\r\n");
      out.write("                      <a href=\"#\" class=\"footer-menu-item\">B:CLE 소개</a>\r\n");
      out.write("                      <a href=\"#\" class=\"footer-menu-item\">동아리 개설</a>\r\n");
      out.write("                      <a href=\"#\" class=\"footer-menu-item\">대표 게시판</a>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"column\">\r\n");
      out.write("                      <div class=\"sub-title\">고객센터</div>\r\n");
      out.write("                      <a href=\"#\" class=\"footer-menu-item\">FAQ</a>\r\n");
      out.write("                      <a href=\"#\" class=\"footer-menu-item\">비회원문의</a>\r\n");
      out.write("                      <a href=\"#\" class=\"footer-menu-item\">이용약관</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"column\">\r\n");
      out.write("                      <div class=\"sub-title\">Contact Us</div>\r\n");
      out.write("                      <a href=\"#\" class=\"footer-menu-item\">주소 : 서울특별시 마포구 월드컵북로 21 4층 풍성빌딩</a>\r\n");
      out.write("                      <a href=\"#\" class=\"footer-menu-item\">02)1234-5678</a>\r\n");
      out.write("                      <a href=\"#\" class=\"footer-menu-item\">깃헙 주소</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"second-box\">\r\n");
      out.write("                  <div class=\"icon-box\">\r\n");
      out.write("                      <i class=\"fab fa-instagram icon\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"icon-box\">\r\n");
      out.write("                      <i class=\"fab fa-twitter icon\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"icon-box\">\r\n");
      out.write("                      <i class=\"fab fa-facebook-f icon\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
