/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-12-07 07:01:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class page37_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/FinalProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ViewPage/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1638860509064L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

   request.setCharacterEncoding("UTF-8");
   String cp = request.getContextPath();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>MemberList.jsp</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/*    .left\r\n");
      out.write("   {\r\n");
      out.write("      float: left;\r\n");
      out.write("   }\r\n");
      out.write("   .right\r\n");
      out.write("   {\r\n");
      out.write("      float: right;\r\n");
      out.write("   }\r\n");
      out.write(" */\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write(" MemberList.jsp\r\n");
      out.write("-  관리자페이지>회원관리>전체회원\r\n");
      out.write("\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("   <div>\r\n");
      out.write("      <!-- 메뉴 영역 -->\r\n");
      out.write("      \r\n");
      out.write("      <!-- 콘텐츠 영역 -->\r\n");
      out.write("      <div id=\"content\" style=\"margin-left: 30vh;\">\r\n");
      out.write("         <h1>[ 전체회원 ]</h1>\r\n");
      out.write("         <hr>\r\n");
      out.write("\r\n");
      out.write("         <div>\r\n");
      out.write("            \r\n");
      out.write("            <form action=\"\">\r\n");
      out.write("               <span class=\"left\">\r\n");
      out.write("                  <select name=\"type\">\r\n");
      out.write("                       <option value=\"회원번호순\" selected=\"selected\">회원번호순</option>\r\n");
      out.write("                      <option value=\"신고횟수순\">신고횟수순</option>\r\n");
      out.write("                      <option value=\"개월정지횟수\" >1개월정지횟수</option>\r\n");
      out.write("                      <option value=\"휴면여부\">휴면여부</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("               </span>\r\n");
      out.write("               <span class=\"right\">\r\n");
      out.write("                  <input type=\"text\" value=\"검색어입력\" class=\"search\" />\r\n");
      out.write("                  <button type=\"button\">검색</button>\r\n");
      out.write("               </span>\r\n");
      out.write("            </form>\r\n");
      out.write("         </div>\r\n");
      out.write("      \r\n");
      out.write("         <table id=\"memberList\" class=\"table\" >\r\n");
      out.write("              <tr>\r\n");
      out.write("                 <!-- 항목 8EA -->\r\n");
      out.write("                 <th>회원번호</th>\r\n");
      out.write("                 <th>ID</th>\r\n");
      out.write("                 <th>이름</th>\r\n");
      out.write("                 <th>이메일</th>\r\n");
      out.write("                 <th>닉네임</th>\r\n");
      out.write("                 <th>신고횟수</th>\r\n");
      out.write("                 <th>1개월정지횟수</th>\r\n");
      out.write("                 <th>휴면여부</th>              \r\n");
      out.write("              </tr>\r\n");
      out.write("              \r\n");
      out.write("              <tr>\r\n");
      out.write("                 <td>999</td>\r\n");
      out.write("                 <td>idtest</td>\r\n");
      out.write("                 <td>김기방</td>\r\n");
      out.write("                 <td>kimbang@naver.com</td>\r\n");
      out.write("                 <td>빨간토끼</td>\r\n");
      out.write("                 <td>0</td>\r\n");
      out.write("                 <td>0</td>\r\n");
      out.write("                 <td>X</td>              \r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                 <td>998</td>\r\n");
      out.write("                 <td>idididid</td>\r\n");
      out.write("                 <td>박하유</td>\r\n");
      out.write("                 <td>phy@naver.com</td>\r\n");
      out.write("                 <td>파란기린</td>\r\n");
      out.write("                 <td>0</td>\r\n");
      out.write("                 <td>0</td>\r\n");
      out.write("                 <td>X</td>              \r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                 <td>997</td>\r\n");
      out.write("                 <td>teisdi</td>\r\n");
      out.write("                 <td>홍라온</td>\r\n");
      out.write("                 <td>hongra@gmail.com</td>\r\n");
      out.write("                 <td>파란이구아나</td>\r\n");
      out.write("                 <td>0</td>\r\n");
      out.write("                 <td>1</td>\r\n");
      out.write("                 <td>X</td>              \r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                 <td>996</td>\r\n");
      out.write("                 <td>yeloooo</td>\r\n");
      out.write("                 <td>김하하</td>\r\n");
      out.write("                 <td>haha@gmail.com</td>\r\n");
      out.write("                 <td>분홍토끼</td>\r\n");
      out.write("                 <td>1</td>\r\n");
      out.write("                 <td>0</td>\r\n");
      out.write("                 <td>X</td>              \r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                 <td>995</td>\r\n");
      out.write("                 <td>pinkkkk</td>\r\n");
      out.write("                 <td>마동석</td>\r\n");
      out.write("                 <td>mama@naver.com</td>\r\n");
      out.write("                 <td>분홍솜사탕</td>\r\n");
      out.write("                 <td>1</td>\r\n");
      out.write("                 <td>0</td>\r\n");
      out.write("                 <td>X</td>              \r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                 <td>994</td>\r\n");
      out.write("                 <td>test1122</td>\r\n");
      out.write("                 <td>소방사</td>\r\n");
      out.write("                 <td>sooooo@gmail.com</td>\r\n");
      out.write("                 <td>소방관이요</td>\r\n");
      out.write("                 <td>0</td>\r\n");
      out.write("                 <td>0</td>\r\n");
      out.write("                 <td>O</td>              \r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                 <td>993</td>\r\n");
      out.write("                 <td>pppap</td>\r\n");
      out.write("                 <td>호현아</td>\r\n");
      out.write("                 <td>tiger@naver.com</td>\r\n");
      out.write("                 <td>호랑이다</td>\r\n");
      out.write("                 <td>0</td>\r\n");
      out.write("                 <td>0</td>\r\n");
      out.write("                 <td>X</td>              \r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                 <td>992</td>\r\n");
      out.write("                 <td>testests1</td>\r\n");
      out.write("                 <td>김낑깡</td>\r\n");
      out.write("                 <td>kim123@naver.com</td>\r\n");
      out.write("                 <td>노란낑깡</td>\r\n");
      out.write("                 <td>2</td>\r\n");
      out.write("                 <td>0</td>\r\n");
      out.write("                 <td>X</td>              \r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                 <td>991</td>\r\n");
      out.write("                 <td>tethihih</td>\r\n");
      out.write("                 <td>이하이</td>\r\n");
      out.write("                 <td>hihi@gmail.com</td>\r\n");
      out.write("                 <td>하이하이하</td>\r\n");
      out.write("                 <td>0</td>\r\n");
      out.write("                 <td>2</td>\r\n");
      out.write("                 <td>X</td>              \r\n");
      out.write("              </tr>\r\n");
      out.write("              \r\n");
      out.write("              </table>\r\n");
      out.write("        \r\n");
      out.write("           \r\n");
      out.write("        <div id=\"footer\">\r\n");
      out.write("         <p>1 Prev 21 22 23 24 25 26 27 28 29 30 Next 54</p>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      </div>   \r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("       </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
