/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2021-12-11 14:40:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("   rel=\"stylesheet\"\r\n");
      out.write("   integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\r\n");
      out.write("   crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<title>Employees List</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@import\r\n");
      out.write("   url('https://fonts.googleapis.com/css?family=Exo+2|Noto+Sans+KR&display=swap')\r\n");
      out.write("   ;\r\n");
      out.write("\r\n");
      out.write(".row p {\r\n");
      out.write("   font-size: 10px;\r\n");
      out.write("   margin-left: 3vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row {\r\n");
      out.write("   margin-left: 10%;\r\n");
      out.write("   margin-top: 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-footer {\r\n");
      out.write("   display: flex;\r\n");
      out.write("   flex-wrap: wrap;\r\n");
      out.write("   flex-shrink: 0;\r\n");
      out.write("   align-items: center;\r\n");
      out.write("   justify-content: center;\r\n");
      out.write("   padding: .75rem;\r\n");
      out.write("   border-top: 0px solid #dee2e6;\r\n");
      out.write("   border-bottom-right-radius: calc(.3rem - 1px);\r\n");
      out.write("   border-bottom-left-radius: calc(.3rem - 1px);\r\n");
      out.write("   padding: .75rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-secondary {\r\n");
      out.write("   color: #fff;\r\n");
      out.write("   background-color: #6c757d;\r\n");
      out.write("   border-color: #6c757d;\r\n");
      out.write("   margin-right: 7vh;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- modal button -->\r\n");
      out.write("   <div>\r\n");
      out.write("      <a href=\"#\" id=\"modal1\" class=\"btn btn-success btn-sm\"\r\n");
      out.write("         data-bs-toggle=\"modal\" data-bs-target=\"#employee_details1\">평가하기</a>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- Modal -->\r\n");
      out.write("   <!-- 평가 창 -->\r\n");
      out.write("\r\n");
      out.write("   <div class=\"modal fade\" id=\"employee_details1\" tabindex=\"-1\"\r\n");
      out.write("      aria-labelledby=\"employee_details1\" aria-hidden=\"true\">\r\n");
      out.write("      <div class=\"modal-dialog\">\r\n");
      out.write("         <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("               <h5 class=\"modal-title\" id=\"exampleModalLabel\">개인평가</h5>\r\n");
      out.write("               <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("                  aria-label=\"닫기\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"col-lg-4\">\r\n");
      out.write("                  <a href=\"#\"> <svg class=\"bd-placeholder-img rounded-circle\"\r\n");
      out.write("                        width=\"80\" height=\"80\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                        role=\"img\" aria-label=\"Placeholder: 80x80\"\r\n");
      out.write("                        preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("               <title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("                           fill=\"#777\" />\r\n");
      out.write("               <text x=\"50%\" y=\"50%\" fill=\"#777\" dy=\".3em\">80x80</text></svg>\r\n");
      out.write("\r\n");
      out.write("                     <p>닉네임</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <!-- /.col-lg-4 -->\r\n");
      out.write("               <div class=\"col-lg-4\">\r\n");
      out.write("                  <a href=\"#\"> <svg class=\"bd-placeholder-img rounded-circle\"\r\n");
      out.write("                        width=\"80\" height=\"80\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                        role=\"img\" aria-label=\"Placeholder: 80x80\"\r\n");
      out.write("                        preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("               <title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("                           fill=\"#777\" />\r\n");
      out.write("               <text x=\"50%\" y=\"50%\" fill=\"#777\" dy=\".3em\">80x80</text></svg>\r\n");
      out.write("\r\n");
      out.write("                     <p>닉네임</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <!-- /.col-lg-4 -->\r\n");
      out.write("               <div class=\"col-lg-4\">\r\n");
      out.write("                  <a href=\"#\"> <svg class=\"bd-placeholder-img rounded-circle\"\r\n");
      out.write("                        width=\"80\" height=\"80\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                        role=\"img\" aria-label=\"Placeholder: 80x80\"\r\n");
      out.write("                        preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("               <title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("                           fill=\"#777\" />\r\n");
      out.write("               <text x=\"50%\" y=\"50%\" fill=\"#777\" dy=\".3em\">80x80</text></svg>\r\n");
      out.write("\r\n");
      out.write("                     <p>닉네임</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <!-- /.col-lg-4 -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"col-lg-4\">\r\n");
      out.write("                  <a href=\"modal2.jsp\"> <svg\r\n");
      out.write("                        class=\"bd-placeholder-img rounded-circle\" width=\"80\" height=\"80\"\r\n");
      out.write("                        xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("                        aria-label=\"Placeholder: 80x80\"\r\n");
      out.write("                        preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("               <title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("                           fill=\"#777\" />\r\n");
      out.write("               <text x=\"50%\" y=\"50%\" fill=\"#777\" dy=\".3em\">80x80</text></svg>\r\n");
      out.write("\r\n");
      out.write("                     <p>닉네임</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <!-- /.col-lg-4 -->\r\n");
      out.write("               <div class=\"col-lg-4\">\r\n");
      out.write("                  <a href=\"#\"> <svg class=\"bd-placeholder-img rounded-circle\"\r\n");
      out.write("                        width=\"80\" height=\"80\" xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("                        role=\"img\" aria-label=\"Placeholder: 80x80\"\r\n");
      out.write("                        preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("               <title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("                           fill=\"#777\" />\r\n");
      out.write("               <text x=\"50%\" y=\"50%\" fill=\"#777\" dy=\".3em\">80x80</text></svg>\r\n");
      out.write("\r\n");
      out.write("                     <p>닉네임</p>\r\n");
      out.write("                  </a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <!-- /.col-lg-4 -->\r\n");
      out.write("               <!-- 이중모달 연결 -->\r\n");
      out.write("               <div class=\"col-lg-4\">\r\n");
      out.write("                  <a href=\"#\" data-bs-toggle=\"modal\"\r\n");
      out.write("                     data-bs-target=\"#employee_details2\"> <svg\r\n");
      out.write("                        class=\"bd-placeholder-img rounded-circle\" width=\"80\" height=\"80\"\r\n");
      out.write("                        xmlns=\"http://www.w3.org/2000/svg\" role=\"img\"\r\n");
      out.write("                        aria-label=\"Placeholder: 80x80\"\r\n");
      out.write("                        preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("               <title>Placeholder</title><rect width=\"100%\" height=\"100%\"\r\n");
      out.write("                           fill=\"#777\" />\r\n");
      out.write("               <text x=\"50%\" y=\"50%\" fill=\"#777\" dy=\".3em\">80x80</text></svg>\r\n");
      out.write("\r\n");
      out.write("                     <p>닉네임</p></a> </a>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <div></div>\r\n");
      out.write("               <!-- /.col-lg-4 -->\r\n");
      out.write("               <div class=\"modal-footer\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("                     data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"modal fade\" id=\"employee_details2\" tabindex=\"-1\"\r\n");
      out.write("                  aria-labelledby=\"employee_details2\" aria-hidden=\"true\">\r\n");
      out.write("                  <div class=\"modal-dialog\">\r\n");
      out.write("                     <div class=\"modal-content\">\r\n");
      out.write("                        <div class=\"modal-header\">\r\n");
      out.write("                           <h5 class=\"modal-title\" id=\"exampleModalLabel\">TO. 차분한포카칩\r\n");
      out.write("                              님,</h5>\r\n");
      out.write("                           <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("                              aria-label=\"닫기\"></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <form>\r\n");
      out.write("                           <div class=\"modal-body\">\r\n");
      out.write("                              <input type=\"checkbox\" name=\"rate\"> &nbsp;시간약속을 잘 지켜요<br>\r\n");
      out.write("                              <input type=\"checkbox\" name=\"rate\"> &nbsp;친절하고 매너가 좋아요<br>\r\n");
      out.write("                              <input type=\"checkbox\" name=\"rate\"> &nbsp;적극적으로 참여해요<br>\r\n");
      out.write("                              <input type=\"checkbox\" name=\"rate\"> &nbsp;다른 회원의 말에 귀\r\n");
      out.write("                              기울여줘요<br> <input type=\"checkbox\" name=\"rate\">\r\n");
      out.write("                              &nbsp;회원들을 재밌게 해줘요<br> <input type=\"checkbox\" name=\"rate\">\r\n");
      out.write("                              &nbsp;사전 준비를 잘해요<br> <input type=\"checkbox\" name=\"rate\">\r\n");
      out.write("                              &nbsp;동아리 분위기를 잘 띄워줘요<br> <br>\r\n");
      out.write("                              <br>\r\n");
      out.write("                              <br> <input type=\"checkbox\" name=\"rate\">\r\n");
      out.write("                              &nbsp;동아리 활동을 지연 시켜요<br> <input type=\"checkbox\"\r\n");
      out.write("                                 name=\"rate\"> &nbsp;불친절하고 매너가 좋지 못해요<br> <input\r\n");
      out.write("                                 type=\"checkbox\" name=\"rate\"> &nbsp;소극적으로 참여해요<br>\r\n");
      out.write("                              <input type=\"checkbox\" name=\"rate\"> &nbsp;다른 회원을 무시해요<br>\r\n");
      out.write("                              <input type=\"checkbox\" name=\"rate\"> &nbsp;금전적인 문제를\r\n");
      out.write("                              일으켜요<br> <input type=\"checkbox\" name=\"rate\">\r\n");
      out.write("                              &nbsp;타인에게 지나친 관심을 표현해요<br>\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                     </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js\"\r\n");
      out.write("      integrity=\"sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js\"\r\n");
      out.write("      integrity=\"sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
      out.write("   <script>\r\n");
      out.write("      $(document).ready(function()\r\n");
      out.write("      {\r\n");
      out.write("\r\n");
      out.write("         $('#employee_details2').on('beforeShow', function()\r\n");
      out.write("         {\r\n");
      out.write("            console.log('Submodal beforeShow event');\r\n");
      out.write("         }).on('show', function()\r\n");
      out.write("         {\r\n");
      out.write("            console.log('Submodal show event');\r\n");
      out.write("         }).on('beforeHide', function()\r\n");
      out.write("         {\r\n");
      out.write("            console.log('Submodal beforeHide event');\r\n");
      out.write("         }).on('hide', function()\r\n");
      out.write("         {\r\n");
      out.write("            console.log('Submodal hide event');\r\n");
      out.write("         });\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
